import { Button, VerticalBox, ListView, ProgressIndicator, HorizontalBox } from "std-widgets.slint";


export component EncryptionPage inherits Window {
    preferred-width: 600px;
    preferred-height: 600px;
    in-out property <{path: string, time: int}> time_data;
    title: "Encrypt " + time_data.path + " - Contain";
    callback request-open-file();
    VerticalBox {
        Rectangle {
            border-width: 1px;
            border-color: black;
            border-radius: 12px;
            height: 10%;
            width: 80%;
            HorizontalBox {
                Text {
                    text: "Minutes";
                }
                TextInput {
                    input-type : InputType.number;
                    text: ;
                }
            }   
        }

        HorizontalLayout {
            padding: 10px;
            height: 12%;
            spacing: 15px;
            Rectangle {
                border-width: 1px;
                border-color: black;
                border-radius: 12px;
                Button {
                    width: 100%;
                    height: 100%;
                    text: "Cancel";
                    clicked => {
                        //todo
                    }
                }
            }

            Rectangle {
                border-width: 1px;
                border-color: black;
                border-radius: 12px;
                Button {
                    width: 100%;
                    height: 100%;
                    text: "Ok";
                    clicked => {
                        root.request-open-file();
                    }
                }
            }
        }
    }
}
