import { Button, VerticalBox, ListView, ProgressIndicator, HorizontalBox } from "std-widgets.slint";


export component EncryptionPage inherits Window {
    preferred-width: 600px;
    preferred-height: 600px;
    title: "Encryption File - Contain";
    in-out property <[{path: string, time: int}]> time_data;
    callback request-open-file();
    VerticalBox {
        Rectangle {
            height: 78%;
            width: 80%;
            VerticalBox {
                //todo
            }   
        }

        HorizontalLayout {
            padding: 10px;
            height: 12%;
            spacing: 10px;
            Rectangle {
                border-width: 1px;
                border-color: black;
                border-radius: 12px;
                Button {
                    width: 100%;
                    height: 100%;
                    text: "Cancel";
                    clicked => {
                        //todo
                    }
                }
            }

            Rectangle {
                border-width: 1px;
                border-color: black;
                border-radius: 12px;
                Button {
                    width: 100%;
                    height: 100%;
                    text: "Ok";
                    clicked => {
                        root.request-open-file();
                    }
                }
            }
        }
    }
}
