import { Button, VerticalBox } from "std-widgets.slint";

export component MyApp inherits Window {
    preferred-width: 600px;
    preferred-height: 600px;
    in-out property<string> info: "empty";
    callback request-open-file();
    VerticalBox {
        Text {
            text: "Files \{root.info}";
        }
        Button {
            text: "Get File";
            clicked => {
                root.request-open-file();
            }
        }
    }
}